# Generated by Django 3.2.3 on 2021-05-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='importance',
            field=models.SmallIntegerField(choices=[(0, 'very important'), (1, 'important'), (2, 'least important')]),
        ),
    ]
